name: Delete merged branches

on:
  workflow_call:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == github.event.repository.default_branch
    runs-on: ubuntu-latest

    steps:
      - name: Delete source branch after merge into default branch
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.pull_request.head.ref;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const defaultBranch = context.payload.repository.default_branch;

            // Safety checks
            if (branch === defaultBranch || branch === 'main' || branch === 'master') {
              console.log('Skipping deletion of protected branch');
              return;
            }

            try {
              await github.rest.git.deleteRef({
                owner,
                repo,
                ref: `heads/${branch}`
              });
              console.log(`Successfully deleted branch: ${branch}`);
            } catch (error) {
              console.log(`Failed to delete branch ${branch}: ${error.message}`);
            }